services:
  redis:
    image: redis
    volumes:
      - ./data:/data
  library:
    build: .
    ports:
      - 80:8000
    environment:
      - PORT=8000
  counter:
    build: ./counter
    ports:
      - 81:9080
    environment:
      - PORT=9080
      - REDIS_URL=redis://redis
    depends_on:
      - redis
